version: '3.20'
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./api:/app
      - ./api/requirements.txt:/app/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1
  app:
    build:
      context: ./app
    ports:
      - "5002:5000"
    volumes:
      - ./app:/usr/src/app
    command: yarn dev
    