version: "3.25"
services:
  api-shotpredict:
    build:
      context: .
      dockerfile: api-shotpredict/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./api-shotpredict:/app
      - ./api-shotpredict/requirements.txt:/app/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1

  api-liverecording:
    build:
      context: .
      dockerfile: api-liverecording/Dockerfile
    volumes:
      - ./api-liverecording:/app
      - ./api-liverecording/requirements.txt:/app/requirements.txt
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1

  app:
    build:
      context: ./app
    ports:
      - "5002:5000"
    volumes:
      - ./app:/usr/src/app
    command: yarn dev
